openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - App
info:
  title: Gatheraa API v2
  description: Runtime generated OpenAPI specification for Gatheraa API v2
  version: '2.0'
  contact: {}
tags: []
servers: []
components:
  schemas: {}
